---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-16.04
    driver_config:
      network:
      - ["private_network", {ip: "10.10.10.22" } ]

suites:
  - name: default
    run_list:
      - recipe[managed-dns::default]
    attributes:
